### ISSUE TITLE
Bitcorn Bot improvement 

### ISSUE THREAD

**Issue by aaliakbari** [BITCORNProject/BITCORN-oldchain#10]
# Report an issue or request a feature 

* **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request
  
## If this is a feature request, what would you like to see?
Discord improvement to BitcornBot, ROI and reward/day

## Additional information
![image](https://user-images.githubusercontent.com/19491006/61162677-ea4c9480-a51e-11e9-95ce-826f152b9a1e.png)

**Comment by cisnes** [comment]
Those API endpoints were lost during the previous explorer-upgrade so I was forced to remove it from the bot. We are planning on creating a backup-explorer supporting those API endpoints to be able to get the data, but there's not a ETA yet.

**Comment by JasonSowers** [comment]
This is now fixed
