### ISSUE TITLE
bitcornfaucet down

### ISSUE THREAD

**Issue by aaliakbari** [BITCORNProject/BITCORN-oldchain#11]
# Report an issue or request a feature 

* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  
## What operating system and browser (if applicable) are you using?
Chrome Version 75.0.3770.100 (Official Build) Windows 10 64Bit

## What went wrong

https://bitcornfaucet.com went down

## Additional information
![image](https://user-images.githubusercontent.com/19491006/61162735-53340c80-a51f-11e9-95e9-c329119e223e.png)

**Comment by bitcornfarmer** [comment]
Has been resolved.
