### ISSUE TITLE
BitcornProject MN count

### ISSUE THREAD

**Issue by aaliakbari** [BITCORNProject/BITCORN-oldchain#12]
# Report an issue or request a feature 

* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  
## What operating system and browser (if applicable) are you using?
Chrome Version 75.0.3770.100 (Official Build) Windows 10 64Bit

## What went wrong

https://bitcornproject.com/ MN count and Coin Rewards does not match with explorer

## Additional information
![image](https://user-images.githubusercontent.com/19491006/61162785-93938a80-a51f-11e9-9c74-f2d0ef9a2a2b.png)

**Comment by bitcornfarmer** [comment]
This is not a real time number.  The number is updated manually.
