### ISSUE TITLE
QT wallet Locked Coin part

### ISSUE THREAD

**Issue by aaliakbari** [BITCORNProject/BITCORN-oldchain#5]
# Report an issue or request a feature 

* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  
## What operating system and browser (if applicable) are you using?
Windows 10 64Bit

## What went wrong

The Locked coins part of Blockchain info in QT wallet is wrong and negative 

## Additional information
![image](https://user-images.githubusercontent.com/19491006/61162120-5f6a9a80-a51c-11e9-863e-04db0291aa00.png)

**Comment by JasonSowers** [comment]
This has since been fixed, thank you for reporting this
